<?php 
    $dbcon = mysqli_connect("localhost","root","poppom22936","final") or die(mysqli_error());
    if (mysqli_connect_error()){
        echo"can not connext Database";
    }
    mysqli_set_charset($dbcon,'utf8');

    $title_service = $_POST['title_service'];
    $topic_ct_service1 = $_POST['topic_ct_service1'];
    $detail_ct_service1 = $_POST['detail_ct_service1'];
    $topic_ct_service2 = $_POST['topic_ct_service2'];
    $topic_A = $_POST['topic_A'];
    $detail_A = $_POST['detail_A'];
    $topic_B = $_POST['topic_B'];
    $detail_B = $_POST['detail_B'];
    $topic_C = $_POST['topic_C'];
    $detail_C = $_POST['detail_C'];
    $sup_topic_C1 = $_POST['sup_topic_C1'];
    $sup_topic_C2 = $_POST['sup_topic_C2'];
    $sup_topic_C3 = $_POST['sup_topic_C3'];
    $topic_D = $_POST['topic_D'];
    $detail_D = $_POST['detail_D'];
    $sup_topic_D1 = $_POST['sup_topic_D1'];
    $sup_topic_D2 = $_POST['sup_topic_D2'];
    $sup_topic_D3 = $_POST['sup_topic_D3'];
    $sup_topic_D4 = $_POST['sup_topic_D4'];
    $topic_E = $_POST['topic_E'];
    $detail_E = $_POST['detail_E'];
    $sup_topic_E1 = $_POST['sup_topic_E1'];
    $sup_topic_E2 = $_POST['sup_topic_E2'];
    $sup_topic_E3 = $_POST['sup_topic_E3'];
    $sup_topic_E4 = $_POST['sup_topic_E4'];
    $topic_F = $_POST['topic_F'];
    $detail_F = $_POST['detail_F'];
    $sup_topic_F1 = $_POST['sup_topic_F1'];
    $sup_topic_F2 = $_POST['sup_topic_F2'];
    $sup_topic_F3 = $_POST['sup_topic_F3'];
    $sup_topic_F4 = $_POST['sup_topic_F4'];
    $sup_topic_F5 = $_POST['sup_topic_F5'];
    $sup_topic_F6 = $_POST['sup_topic_F6'];
    $topic_G = $_POST['topic_G'];
    $detail_G = $_POST['detail_G'];
    $topic_H = $_POST['topic_H'];
    $detail_H = $_POST['detail_H'];
    $topic_I = $_POST['topic_I'];
    $sup_topic_I1 = $_POST['sup_topic_I1'];
    $sup_topic_I2 = $_POST['sup_topic_I2'];
    $sup_topic_I3 = $_POST['sup_topic_I3'];
    $sup_topic_I4 = $_POST['sup_topic_I4'];
    $sup_topic_I5 = $_POST['sup_topic_I5'];
    $sup_topic_I6 = $_POST['sup_topic_I6'];
    $topic_K = $_POST['topic_K'];
    $detail_K = $_POST['detail_K'];
    $topic_ct_service3 = $_POST['topic_ct_service3'];
    $topic_price1 = $_POST['topic_price1'];
    $price1 = $_POST['price1'];
    $detail_price1_1 = $_POST['detail_price1_1'];
    $detail_price1_2 = $_POST['detail_price1_2'];
    $detail_price1_3 = $_POST['detail_price1_3'];
    $detail_price1_4 = $_POST['detail_price1_4'];
    $topic_price2 = $_POST['topic_price2'];
    $price2 = $_POST['price2'];
    $detail_price2_1 = $_POST['detail_price2_1'];
    $detail_price2_2 = $_POST['detail_price2_2'];
    $detail_price2_3 = $_POST['detail_price2_3'];
    $detail_price2_4 = $_POST['detail_price2_4'];
    $topic_price3 = $_POST['topic_price3'];
    $price3 = $_POST['price3'];
    $detail_price3_1 = $_POST['detail_price3_1'];
    $detail_price3_2 = $_POST['detail_price3_2'];
    $detail_price3_3 = $_POST['detail_price3_3'];
    $detail_price3_4 = $_POST['detail_price3_4'];



     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$title_service' WHERE `vn`.`id` = 59;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_ct_service1' WHERE `vn`.`id` = 60;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_ct_service1' WHERE `vn`.`id` = 61;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_ct_service2' WHERE `vn`.`id` = 62;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_A' WHERE `vn`.`id` = 63;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_A' WHERE `vn`.`id` = 64;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_B' WHERE `vn`.`id` = 65;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_B' WHERE `vn`.`id` = 66;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_C' WHERE `vn`.`id` = 67;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_C' WHERE `vn`.`id` = 68;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_C1' WHERE `vn`.`id` = 69;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_C2' WHERE `vn`.`id` = 70;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_C3' WHERE `vn`.`id` = 71;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_D' WHERE `vn`.`id` = 72;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_D' WHERE `vn`.`id` = 73;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_D1' WHERE `vn`.`id` = 74;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_D2' WHERE `vn`.`id` = 75;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_D3' WHERE `vn`.`id` = 76;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_D4' WHERE `vn`.`id` = 77;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_E' WHERE `vn`.`id` = 78;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_E' WHERE `vn`.`id` = 79;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_E1' WHERE `vn`.`id` = 80;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_E2' WHERE `vn`.`id` = 81;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_E3' WHERE `vn`.`id` = 82;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_E4' WHERE `vn`.`id` = 83;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_F' WHERE `vn`.`id` = 84;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_F' WHERE `vn`.`id` = 85;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F1' WHERE `vn`.`id` = 86;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F2' WHERE `vn`.`id` = 87;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F3' WHERE `vn`.`id` = 88;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F4' WHERE `vn`.`id` = 89;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F5' WHERE `vn`.`id` = 90;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_F6' WHERE `vn`.`id` = 91;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_G' WHERE `vn`.`id` = 92;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_G' WHERE `vn`.`id` = 93;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_H' WHERE `vn`.`id` = 94;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_H' WHERE `vn`.`id` = 95;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_I' WHERE `vn`.`id` = 96;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I1' WHERE `vn`.`id` = 97;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I2' WHERE `vn`.`id` = 98;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I3' WHERE `vn`.`id` = 99;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I4' WHERE `vn`.`id` = 100;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I5' WHERE `vn`.`id` = 101;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$sup_topic_I6' WHERE `vn`.`id` = 102;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_K' WHERE `vn`.`id` = 103;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_K' WHERE `vn`.`id` = 104;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_ct_service3' WHERE `vn`.`id` = 105;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_price1' WHERE `vn`.`id` = 106;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$price1' WHERE `vn`.`id` = 107;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price1_1' WHERE `vn`.`id` = 108;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price1_2' WHERE `vn`.`id` = 109;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price1_3' WHERE `vn`.`id` = 110;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price1_4' WHERE `vn`.`id` = 111;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_price2' WHERE `vn`.`id` = 112;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$price2' WHERE `vn`.`id` = 113;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price2_1' WHERE `vn`.`id` = 114;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price2_2' WHERE `vn`.`id` = 115;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price2_3' WHERE `vn`.`id` = 116;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price2_4' WHERE `vn`.`id` = 117;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$topic_price3' WHERE `vn`.`id` = 118;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$price3' WHERE `vn`.`id` = 119;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price3_1' WHERE `vn`.`id` = 120;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price3_2' WHERE `vn`.`id` = 121;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price3_3' WHERE `vn`.`id` = 122;");
     mysqli_query($dbcon,"UPDATE `vn` SET `content` = '$detail_price3_4' WHERE `vn`.`id` = 123;");

    header('Location:../Admin/Servics1Admin.php');
?>